# Generated by Django 2.2.18 on 2021-02-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myschedule',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='presenter',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='vendordetail',
            name='vendor_id',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
