# Generated by Django 2.2.18 on 2021-02-07 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210207_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='Presenter',
        ),
    ]
